Repository two-clock/backend, pull requests merged in 2024-09, with the labels that each got.

#83 feat: Image file deletion processing when editing or deleting a boards
  src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardRequestDto.java
  src/main/java/com/twoclock/gitconnect/domain/board/entity/Board.java
  src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardFileRepository.java
  src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java
  src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java
  src/main/java/com/twoclock/gitconnect/global/s3/S3Service.java
Labels: feature

#87 fix: Improve JWT handling, enhance security settings, and update CORS configuration
  src/main/java/com/twoclock/gitconnect/domain/member/service/MemberAuthService.java
  src/main/java/com/twoclock/gitconnect/domain/member/web/MemberAuthController.java
  src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java
  src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java
  src/main/java/com/twoclock/gitconnect/global/jwt/service/JwtService.java
  src/main/java/com/twoclock/gitconnect/global/security/JwtAuthenticationFilter.java
  src/main/java/com/twoclock/gitconnect/global/security/JwtExceptionFilter.java
  src/main/java/com/twoclock/gitconnect/global/util/CookieUtil.java
Labels: feature

#88 feat: add board details view API addition and caching processing
  src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardDetailRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/board/entity/Board.java
  src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java
  src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java
  src/main/java/com/twoclock/gitconnect/domain/comment/dto/CommentListRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/like/dto/LikesRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/like/repository/LikeRepository.java
  src/main/java/com/twoclock/gitconnect/domain/member/dto/MemberLoginRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/member/service/MemberService.java
  src/main/java/com/twoclock/gitconnect/global/config/RedisConfig.java
  src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java
Labels: feature

#91 feat: Create endpoint for fetching boards by category
  src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardWithCategoryRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardFileRepository.java
  src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardRepository.java
  src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java
  src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java
  src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java
  src/main/java/com/twoclock/gitconnect/global/dummy/DummyDevlnit.java
Labels: feature

#95 refactor: Add keyword search functionality to board listings
  src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardRepository.java
  src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java
  src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java
Labels: refactor

#99 test: Add dummy data test with Faker library
  build.gradle
  src/test/java/com/twoclock/gitconnect/data/DummyDataTest.java
Labels: test

#102 refactor: when get a boardDetailAPI, images are also viewed
  src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardDetailRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardFileRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java
Labels: refactor

#105 fix: Add Comment Response Feild and when modify and delete to verify
  src/main/java/com/twoclock/gitconnect/domain/board/entity/Board.java
  src/main/java/com/twoclock/gitconnect/domain/comment/dto/CommentListRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/comment/entity/Comment.java
  src/main/java/com/twoclock/gitconnect/domain/comment/service/CommentService.java
  src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java
Labels: bug, refactor

#106 bug: Increased number of views when viewing detailed boards
  src/main/java/com/twoclock/gitconnect/domain/board/entity/Board.java
  src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardRepository.java
  src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java
  src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java
Labels: bug, refactor

#107 refactor: Refactor createChatRoom to use receiveLogin parameter
  src/main/java/com/twoclock/gitconnect/domain/chat/dto/ChatMessageRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/chat/dto/ChatRoomRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/chat/service/ChatMessageService.java
  src/main/java/com/twoclock/gitconnect/domain/chat/service/ChatRoomService.java
  src/main/java/com/twoclock/gitconnect/domain/chat/web/ChatRoomController.java
  src/main/java/com/twoclock/gitconnect/global/dummy/DummyDevlnit.java
Labels: refactor

#112 refactor: Change like retrieval endpoint to verify user like
  src/main/java/com/twoclock/gitconnect/domain/like/service/LikeService.java
  src/main/java/com/twoclock/gitconnect/domain/like/web/LikeController.java
Labels: feature

#110 refactor: Add like, view count to BoardDetail response
  src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardDetailRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java
  src/main/java/com/twoclock/gitconnect/domain/like/repository/LikeRepository.java
Labels: refactor

#113 feat: add regist notification and read notification
  src/main/java/com/twoclock/gitconnect/domain/chat/service/ChatMessageService.java
  src/main/java/com/twoclock/gitconnect/domain/comment/service/CommentService.java
  src/main/java/com/twoclock/gitconnect/domain/like/service/LikeService.java
  src/main/java/com/twoclock/gitconnect/domain/notification/dto/NotificationRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/notification/entity/Notification.java
  src/main/java/com/twoclock/gitconnect/domain/notification/entity/constants/NotificationType.java
  src/main/java/com/twoclock/gitconnect/domain/notification/repository/NotificationRepository.java
  src/main/java/com/twoclock/gitconnect/domain/notification/service/NotificationService.java
  src/main/java/com/twoclock/gitconnect/domain/notification/web/NotificationController.java
  src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java
  src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java
Labels: feature

#115 feat: Implement weekly popular members and repositories based on likes
  src/main/java/com/twoclock/gitconnect/domain/like/dto/LikePopularWeekMemberRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/like/dto/LikePopularWeekRepositoryRespDto.java
  src/main/java/com/twoclock/gitconnect/domain/like/entity/Likes.java
  src/main/java/com/twoclock/gitconnect/domain/like/repository/CustomLikeRepository.java
  src/main/java/com/twoclock/gitconnect/domain/like/repository/LikeRepository.java
  src/main/java/com/twoclock/gitconnect/domain/like/repository/LikeRepositoryImpl.java
  src/main/java/com/twoclock/gitconnect/domain/like/service/LikeService.java
  src/main/java/com/twoclock/gitconnect/domain/like/web/LikeController.java
  src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java
  src/main/java/com/twoclock/gitconnect/global/dummy/DummyDevlnit.java
  src/test/java/com/twoclock/gitconnect/domain/like/service/LikeServiceTest.java
Labels: feature

#119 feat: add soft delete to notification
  src/main/java/com/twoclock/gitconnect/domain/chat/service/ChatMessageService.java
  src/main/java/com/twoclock/gitconnect/domain/comment/service/CommentService.java
  src/main/java/com/twoclock/gitconnect/domain/like/service/LikeService.java
  src/main/java/com/twoclock/gitconnect/domain/notification/entity/Notification.java
  src/main/java/com/twoclock/gitconnect/domain/notification/service/NotificationService.java
  src/main/java/com/twoclock/gitconnect/domain/notification/web/NotificationController.java
Labels: feature, refactor
